//
//  InPlaceGenerateSheet.swift
//  Kizba
//
//  Phase G.3 — sheet hosted by `EntryDetailView` (toolbar 🎲 button
//  and the `Entry > Regenerate Password` menu item, ⌘⌥G). Lets the
//  user rotate the currently-selected entry's password atomically
//  via `pass generate --in-place`, preserving its metadata block.
//
//  Visually adjacent to `GeneratePasswordSheet.swift` (Phase F.4)
//  but mechanically different: that sheet PREVIEWS a candidate
//  password locally for a NEW entry; this one COMMITS via the CLI
//  for an EXISTING entry — there is no preview because the
//  committed value is the value generated by `pass` itself, not by
//  our local `PasswordGenerating`. Any preview here would be
//  actively misleading.
//
//  All visual styling MUST go through `theme.*` tokens; the Phase
//  C.6 `SourceGrepTests` enforce this for every file under
//  `Kizba/Presentation/**` outside `DesignSystem/**`.
//

import SwiftUI

/// Sub-sheet view for regenerating the password of the currently-
/// selected entry in place.
@MainActor
struct InPlaceGenerateSheet: View {

    /// View-model. `@Bindable` because ``RegenerateInPlaceModel`` is
    /// `@Observable`; the sheet binds to its `length` /
    /// `includeSymbols` properties directly.
    @Bindable var model: RegenerateInPlaceModel

    @Environment(\.dismiss) private var dismiss
    @Environment(\.theme) private var theme

    var body: some View {
        VStack(spacing: theme.spacing.lg) {
            header
            warning
            controls
            errorBlock
            footerActions
        }
        .padding(theme.spacing.lg)
        .frame(minWidth: 420)
        .background(theme.colors.surface)
        // Auto-dismiss on success. The model's `regenerate()` lands
        // in `.succeeded(_)` once both the pre-`show` and the in-
        // place rotation have committed; SwiftUI runs `.onChange`
        // synchronously on the MainActor, so the dismiss happens
        // on the same turn-of-the-runloop as the state mutation.
        .onChange(of: stateID) { _, _ in
            if case .succeeded = model.state { dismiss() }
        }
    }

    // MARK: - Header

    private var header: some View {
        VStack(alignment: .leading, spacing: theme.spacing.xs) {
            Text("Regenerate password")
                .font(theme.typography.title)
                .foregroundStyle(theme.colors.onSurface)
            Text(model.entry.path)
                .font(theme.typography.caption)
                .foregroundStyle(theme.colors.onSurfaceMuted)
                .textSelection(.enabled)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    // MARK: - Warning

    /// Up-front warning so the user understands the destructive
    /// nature of the action BEFORE clicking Regenerate. The undo
    /// affordance is surfaced via the success toast, not here —
    /// per the architect's spec.
    private var warning: some View {
        BannerView(
            severity: .warning,
            title: "This will overwrite the current password.",
            message: "The metadata and notes are preserved. You can undo within 10 seconds via the success toast."
        )
    }

    // MARK: - Controls

    private var controls: some View {
        VStack(spacing: theme.spacing.md) {
            HStack {
                Text("Length")
                    .font(theme.typography.body)
                    .foregroundStyle(theme.colors.onSurface)
                Spacer()
                Stepper(
                    value: $model.length,
                    in: RegenerateInPlaceModel.lengthBounds,
                    step: 1
                ) {
                    Text("\(model.length)")
                        .font(theme.typography.bodyEmphasized)
                        .foregroundStyle(theme.colors.onSurface)
                        .monospacedDigit()
                }
                .labelsHidden()
            }
            Toggle(isOn: $model.includeSymbols) {
                Text("Include symbols")
                    .font(theme.typography.body)
                    .foregroundStyle(theme.colors.onSurface)
            }
            .toggleStyle(.switch)
        }
        .disabled(isRunning)
    }

    // MARK: - Error block

    /// Render the underlying ``PassError``'s human message in a
    /// danger banner when the model is in ``State/failed(_:)``. The
    /// sheet stays open on failure so the user can retry or cancel.
    @ViewBuilder
    private var errorBlock: some View {
        if case .failed(let error) = model.state {
            BannerView(
                severity: .danger,
                title: "Could not regenerate password",
                message: errorMessage(for: error)
            )
        } else {
            EmptyView()
        }
    }

    // MARK: - Footer

    private var footerActions: some View {
        HStack(spacing: theme.spacing.md) {
            Spacer()
            Button("Cancel") {
                dismiss()
            }
            .buttonStyle(.kizba(.ghost))
            .keyboardShortcut(.cancelAction)
            .disabled(isRunning)

            Button("Regenerate") {
                Task { await model.regenerate() }
            }
            .buttonStyle(.kizba(.primary))
            .keyboardShortcut(.defaultAction)
            .disabled(isRunning)
        }
    }

    // MARK: - Derived

    /// Whether the model is currently mid-rotation. Disables the
    /// length / symbols controls + footer actions to prevent
    /// double-clicks racing the in-flight CLI call.
    private var isRunning: Bool {
        if case .running = model.state { return true }
        return false
    }

    /// Stable identifier for the discrete state, suitable for
    /// `.onChange`. We use a derived integer rather than the State
    /// enum directly so the modifier compiles even if `State` ever
    /// gains a non-`Equatable` payload.
    private var stateID: Int {
        switch model.state {
        case .idle:        return 0
        case .running:     return 1
        case .succeeded:   return 2
        case .failed:      return 3
        }
    }

    /// Map a ``PassError`` to a brief user-facing message. Mirrors
    /// the abbreviated rendering used elsewhere in the app for
    /// inline form banners — full diagnostics belong in the
    /// Diagnostics window, not in a sub-sheet.
    private func errorMessage(for error: PassError) -> String {
        switch error {
        case .sourceNotFound(let path):
            return "Entry \(path) was not found in the password store."
        case .invalidLength:
            return "The requested length is not accepted by `pass generate`."
        case .recipientNotFound:
            return "GPG could not resolve a recipient from the store's `.gpg-id`."
        case .timedOut:
            return "The operation took too long and was aborted."
        case .cancelled:
            return "The operation was cancelled."
        default:
            return "An unexpected error occurred. See the Diagnostics window for details."
        }
    }
}
