//
//  RegenerateInPlaceModel.swift
//  Kizba
//
//  Phase G.3 — `@Observable @MainActor` view-model backing the
//  `InPlaceGenerateSheet` presented from `EntryDetailView`'s 🎲
//  toolbar button (and the `Entry > Regenerate Password` ⌘⌥G menu
//  item). Lifecycle is bounded by the sub-sheet's presentation:
//  SwiftUI constructs the model when the sheet appears and discards
//  it on dismissal, so the captured prior secret leaves memory as
//  soon as the rotation either succeeds, fails, or is cancelled.
//
//  Mechanism
//  ---------
//
//  Distinct from the F.4 `GeneratePasswordModel`, which previews a
//  candidate password locally via ``PasswordGenerating`` for a NEW
//  entry. The in-place flow targets an EXISTING entry and is backed
//  by the CLI's `pass generate --in-place <path> <length>` invocation
//  (atomic; preserves metadata + notes). We deliberately do NOT
//  preview the new password locally:
//
//  - The committed password is the value generated by `pass` itself,
//    not whatever our local ``PasswordGenerating`` produced. Showing
//    a preview that does not match the committed value would be
//    actively misleading.
//  - The user's intent at this affordance is "rotate now", not
//    "review-then-rotate" (that flow belongs to `NewEntrySheet` +
//    `GeneratePasswordSheet`).
//
//  Undo
//  ----
//
//  Before invoking the rotation we issue a `pass.show(_:)` to
//  capture the prior body. On success we record an
//  ``UndoableAction/inPlaceGenerate(path:previousSecret:)`` in
//  ``ActionHistory`` (10s window) and post an undoable success
//  toast. The undo path re-inserts the captured body via
//  `pass.insert(force: true)`, restoring both the prior password
//  and the prior metadata.
//
//  Cancellation
//  ------------
//
//  `regenerate()` is `async`: SwiftUI's `Task { ... }` wrapper
//  binds it to the view's lifetime, and dismissing the sheet
//  cancels the surrounding task. Because the model is constructed
//  per-presentation, no explicit `cancel()` seam is needed — the
//  garbage collected state suffices.
//
//  Per `.ai/decisions.md`, the new password is never logged and
//  never crosses the toast boundary; toasts carry only the entry
//  path.
//

import Foundation
import Observation

/// View-model backing ``InPlaceGenerateSheet``.
@Observable
@MainActor
final class RegenerateInPlaceModel {

    /// Discrete state of the regeneration pipeline. The view binds
    /// to ``state`` to render the appropriate progress / error / on-
    /// success affordance and to drive auto-dismissal of the sheet.
    enum State: Sendable, Equatable {
        case idle
        case running
        /// Brief success state. Carries the freshly-generated
        /// password so the view can flash it before the sheet auto-
        /// dismisses; the value is otherwise unused. NEVER logged.
        case succeeded(newPassword: String)
        case failed(PassError)
    }

    // MARK: - Observable state

    /// Current pipeline state. Mutated only via ``regenerate()``.
    private(set) var state: State = .idle

    /// Requested length. Bindable so a `Stepper` can target it.
    var length: Int = 24

    /// Whether to include the symbols character class. Bindable so
    /// a `Toggle` can target it. Mapped to `pass generate --in-place`'s
    /// `-n` flag (inverted) by the model.
    var includeSymbols: Bool = true

    /// UI-level bounds for the length stepper. Defined here (not in
    /// the view) so tests can pin the contract without rendering
    /// SwiftUI. Matches the project-wide 8...128 range used by
    /// `GeneratePasswordModel`.
    static let lengthBounds: ClosedRange<Int> = 8...128

    // MARK: - Dependencies

    /// Target entry. Snapshot at construction time — the model is
    /// per-presentation, so the entry cannot drift mid-flight.
    let entry: PassEntry

    private let passManager: any PassManaging
    private let actionHistory: ActionHistory
    private let toastCenter: ToastCenter
    private let appState: AppState

    // MARK: - Init

    init(
        entry: PassEntry,
        passManager: any PassManaging,
        actionHistory: ActionHistory,
        toastCenter: ToastCenter,
        appState: AppState
    ) {
        self.entry = entry
        self.passManager = passManager
        self.actionHistory = actionHistory
        self.toastCenter = toastCenter
        self.appState = appState
    }

    // MARK: - Actions

    /// Capture the prior secret, invoke `pass generate --in-place`,
    /// record the inverse in ``ActionHistory``, and post an
    /// undoable success toast.
    ///
    /// The two CLI calls are sequenced strictly:
    ///
    ///   1. ``PassManaging/show(_:)`` — captures the prior body so
    ///      Undo can re-insert it. A failure here ABORTS the flow:
    ///      we cannot rotate without an undo target. State lands in
    ///      ``State/failed(_:)`` and an error toast is posted.
    ///   2. ``PassManaging/generateInPlace(_:length:includeSymbols:)``
    ///      — actually rotates the password. A failure here also
    ///      lands in ``State/failed(_:)``; ``ActionHistory`` is left
    ///      untouched (no rotation happened, no inverse to record).
    ///
    /// On success the model lands in
    /// ``State/succeeded(newPassword:)`` and posts a success toast
    /// carrying an Undo action that calls back into
    /// ``ActionHistory/undoLast()`` (fire-and-forget Task; the
    /// banner-action surface is non-throwing).
    func regenerate() async {
        state = .running
        // Phase G.6 — mark the regenerate op as in flight so the
        // toolbars / menu items disable other write surfaces. The
        // op is released in EVERY exit branch below (early returns
        // on `show` failure, `generateInPlace` failure, or success)
        // via the `defer` block.
        appState.beginWrite(.regenerate)
        defer { appState.endWrite(.regenerate) }

        // 1. Capture the prior secret. Without this we cannot offer
        // Undo, so any failure here aborts the rotation outright.
        let previousSecret: PassSecret
        do {
            previousSecret = try await passManager.show(entry)
        } catch let error as PassError {
            state = .failed(error)
            postErrorToast(for: error)
            return
        } catch {
            // Defensive — `PassManaging` is contractually typed-throw
            // PassError, but we handle the generic case to keep this
            // surface honest if the contract ever loosens.
            let wrapped = PassError.shellFailure(exitCode: -1, stderrExcerpt: "")
            state = .failed(wrapped)
            postErrorToast(for: wrapped)
            return
        }

        // 2. Rotate the password atomically.
        let newSecret: PassSecret
        do {
            newSecret = try await passManager.generateInPlace(
                entry,
                length: length,
                includeSymbols: includeSymbols
            )
        } catch let error as PassError {
            state = .failed(error)
            postErrorToast(for: error)
            return
        } catch {
            let wrapped = PassError.shellFailure(exitCode: -1, stderrExcerpt: "")
            state = .failed(wrapped)
            postErrorToast(for: wrapped)
            return
        }

        // 3. Success. Record the inverse first so the toast's Undo
        // action has something to consume, THEN post the toast.
        actionHistory.record(
            .inPlaceGenerate(path: entry.path, previousSecret: previousSecret),
            expiresAfter: .seconds(10)
        )

        // Capture the action history reference into a `nonisolated(unsafe)`
        // local so the closure does not need to capture `self` — keeps
        // the Sendable check on `BannerAction` clean and avoids retain
        // cycles via the model.
        let history = actionHistory
        let undoAction = BannerView.BannerAction(label: "Undo") {
            // Fire-and-forget: the banner action signature is
            // `@MainActor () -> Void` (non-throwing). Errors from the
            // inverse `pass.insert(force: true)` are swallowed here on
            // purpose — `ActionHistory.undoLast()` clears `pending`
            // even on failure (per its documented contract), so the
            // user can move on. A future polish pass could surface
            // the failure as a fresh error toast.
            Task { try? await history.undoLast() }
        }

        let toast = Toast(
            severity: .success,
            title: "Password regenerated",
            // Per `.ai/decisions.md`, toasts NEVER carry secret
            // material — only the entry path is permitted.
            message: entry.path,
            action: undoAction
        )
        toastCenter.post(toast)

        state = .succeeded(newPassword: newSecret.password)
    }

    // MARK: - Private

    /// Surface a failure as a danger toast. Title / message are
    /// generic enough to avoid leaking the underlying stderr; the
    /// inline ``BannerView`` rendered by the sheet (in
    /// ``State/failed(_:)``) carries the ``ErrorPresentation``
    /// detail when available.
    private func postErrorToast(for error: PassError) {
        let toast = Toast(
            severity: .danger,
            title: "Could not regenerate password",
            message: entry.path
        )
        toastCenter.post(toast)
    }
}
